pipeline {
    agent any
    
    stages {
        stage('Git-Checkout') {
            steps {
                // Git checkout step
                git credentialsId: 'tomcatcred', url: 'https://github.com/dkadmin/maven-build-dk.git'
                echo "Checkout successful"
            }
        }
        
        stage('Compile') {
            steps {
                // Maven compile step
                sh script: 'mvn compile'
                echo "Compile successful"
            }
        }
               stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
